name: Deploy react js using GutHub action

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run dist --if-present

      - name: Run test
        run: npm test

      - name: List build directory
        run: ls -al dist

      - name: Output npm error log
        if: failure()
        run: cat /home/runner/.npm/_logs/2024-07-31T00_07_53_159Z-debug-0.log

      - name: Deploy 🚀
        if: success()
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
